version: "3.6"
services:
  easy-notes-app:
    container_name: nodejs-elliot
    image: elliotching/elliot-nodejs
    restart: always
    build: .
    # volumes: 
    #   - type: bind
    #     source: d:/data/db
    #     target: /data/db
    ports:
      - "3003:3000"
    # volumes:
    #   - mongodb_for_elliot_nodejs:/data/db
    links:
      - mongodd
    depends_on:
      - mongodd
  mongodd:
    container_name: mongodd
    image: mongo
    # network_mode: host
    ports:
      - "28017:27017"
    # volumes: 
    #   - type: bind
    #     source: d:/data/db
    #     target: /var/lib/docker/volumes/mongodata
    # volumes:
    #   - "D:\\data\\db\\:/var/lib/docker/volumes/node-easy-notes-app_mongodata/"
    # volumes:
    #   - "./data/db/:/var/lib/docker/volumes"
    # volumes:
    #   - mongodb_for_elliot_nodejs:/data/db
# volumes:
#   mongodb_for_elliot_nodejs:
