version: "3"
services:
       easy-notes-app:
           container_name: nodejs-elliot
           image: elliot/nodejs
           restart: always
           build: .
           ports:
             - "3003:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             
             ports:
               - '27017:27017'