const carnames = [
  "Demon",
  "Bolt",
  "Kazam",
  "Devil",
  "Knockout",
  "Boom Boom",
  "Dust Devil",
  "TO",
  "Bam Bam",
  "Dam Hoover",
  "Burner",
  "Roadrunner",
  "Taz",
  "Burn",
  "Fast Five",
  "Smoke",
  "Racer",
  "Fast and Furious",
  "Brimstone",
  "Race",
  "Furiosa",
  "Firebrand",
  "Fast",
  "Imperator Furiosa",
  "Torch",
  "SpeedX",
  "Hannibal",
  "Torcher",
  "Pacer",
  "Clockwork",
  "Scorch",
  "Pace",
  "Clockwork Orange",
  "Light wave",
  "Divebomb",
  "Dr. Strangeglove",
  "Screech",
  "Blink",
  "Swoosh",
  "Score",
  "Snap",
  "Apollo",
  "TD",
  "Kapow",
  "Zinger",
  "Flickr - GmanViz",
  "Abyss",
  "Black Pearl",
  "Knight Rider",
  "Ace of Spades",
  "Black Widow",
  "Mad Max",
  "Bandit",
  "Blackhawk",
  "Mirage",
  "Batmobile",
  "Dark Knight",
  "Necromancer",
  "Nightshade",
  "Deathrow",
  "Nitro",
  "Black Beauty",
  "Dementor",
  "Panther",
  "Black Diamond",
  "Godfather",
  "Reaper",
  "Black Jack",
  "Greaser",
  "Shadow",
  "Black Magic",
  "Grim",
  "Sirius Black",
  "Black Mamba",
  "Jet Black",
  "Zorro",
  "A-Bomb",
  "Maximus",
  "Double D’s",
  "Fat Man",
  "Gladiator",
  "Big and Tall",
  "Titanic",
  "Nessie",
  "Grande",
  "XXL",
  "Zeus",
  "Great White",
  "Gorilla",
  "High Roller",
  "Everest",
  "MPG",
  "10-Gallon",
  "Payday",
  "Tank",
  "Big Britches",
  "Bigfoot",
  "Steely Stan",
  "Clint",
  "Eminem",
  "Tonk",
  "Dirty Harry",
  "Big Easy",
  "Ford Tough",
  "Goodfella",
  "Jack Sparrow",
  "Diesel",
  "Rocky",
  "Darth",
  "V8",
  "Balboa",
  "Indiana",
  "Motor",
  "Scar Face",
  "Han Solo",
  "Big Daddy",
  "Bond, James Bond",
  "Obi Wan",
  "Lil Lady",
  "Raging Bull",
  "Rambo",
  "Meatball",
  "Apocalypse",
  "Kane",
  "The Sub",
  "Nam",
  "Tarzan",
  "The Chopper",
  "QB",
  "Big Boy",
  "High Fidelity",
  "Drake",
  "Mister Fantastic",
  "Die Hard",
  "Bruno",
  "Hellboy",
  "Mean Girl",
  "Juno",
  "Xena",
  "T Swift",
  "Laura Croft",
  "Eleven",
  "Adele",
  "Peggy",
  "Veep",
  "Bieber",
  "Dorothy",
  "The Bride",
  "Ke$ha",
  "The Wicked Witch",
  "Regina",
  "Bae",
  "Pippi Longstockings",
  "Rey",
  "Bella",
  "Sansa",
  "Princess Leia",
  "Clueless",
  "Elaine",
  "Katniss",
  "Fat Amy",
  "Holly Golightly",
  "Mary Poppins",
  "Romy",
  "Lady Macbeth",
  "Liz Lemon",
  "Elle Woods",
  "Brienne of Tarth",
  "Buffy",
  "Cinderella",
  "Scarlett O’Hara",
  "Little Lady",
  "Tinkerbelle",
  "Warrior Princess",
  "Mystique",
  "Conquest",
  "Tornado",
  "Airbender",
  "Victor",
  "Undertow",
  "Extinction",
  "Marathon",
  "Addict",
  "Brute Force",
  "Fuego",
  "Vapor",
  "Warhammer",
  "Midnight Shadow",
  "Gremlin",
  "Neutrino",
  "Satellite",
  "Goblin",
  "Acid",
  "Storm Chaser",
  "Firestarter",
  "Alpha",
  "Blizzard",
  "Frosty",
  "Rain Man",
  "Boneknapper",
  "Ghost Buster",
  "Shelly",
  "Crossbones",
  "Great White",
  "Sinatra",
  "Diamond",
  "Herbie",
  "Snowball",
  "Draco",
  "Icepick",
  "Stay Puft",
  "Entourage",
  "Marshmallow",
  "Sub Zero",
  "Fang",
  "Miami Vice",
  "Whisper",
  "Fluffer Nutter",
  "Moby Dick",
  "White Noise",
  "Fogger",
  "Polar Bear",
  "White Out",
  "Frostbite",
  "Pop n’ Fresh",
  "White Shadow",
  "Ben-Hur",
  "Madagascar",
  "Emilio",
  "Heracles",
  "Zeppelin",
  "Anders",
  "Zee German",
  "Zander",
  "Sapphira",
  "Zee Swede",
  "Zounds",
  "Baltic",
  "The Foreign Hand",
  "Athena",
  "Gibraltar",
  "The Ambassador’s Daughter",
  "Amalfi",
  "Norsk",
  "Ibiza",
  "Tagliatelle",
  "Tripoli",
  "Bombay",
  "Pandora",
  "Persia",
  "Doomsday",
  "Arnold",
  "Michael Jordan",
  "Gravedigger",
  "The Crib",
  "Slammer",
  "Rt. 66",
  "Redbull",
  "Hades",
  "The Crypt",
  "Monster",
  "Pearly Tailgate",
  "Poppa",
  "Bonecrusher",
  "Summer Vacation",
  "Uncle Jeb",
  "Basketcase",
  "Bob the Destroyer",
  "The Donald",
  "Tone Zone",
  "Sweet Caroline",
  "Big Red",
  "Dynamite",
  "Red Bull",
  "Blazing Saddles",
  "Ferris Bueller",
  "Red Hot",
  "Blood Diamond",
  "Highway to Hell",
  "Red October",
  "Bloodshot",
  "Ignite",
  "Road Rage",
  "Bloodsoaked Champion",
  "Komoda",
  "Ron Burgundy",
  "Bloody Murder",
  "Ladybug",
  "Rosanne",
  "Cherry Bomb",
  "Lightning McQueen",
  "Starsky",
  "Clifford, the Big Red Car",
  "Magnum PI",
  "Taurus",
  "Crimson Machine",
  "Merlot",
  "TNT",
  "Diablo",
  "Nightcrawler",
  "Yosemite Sam",
  "Peanut",
  "Dolly",
  "My Neopet",
  "Munchkin",
  "Bon Bon",
  "Furby",
  "Donut Hole",
  "Wheat Thin",
  "Baby Grand",
  "Teacup",
  "Babe",
  "Kid’s Menu",
  "Fun Size",
  "Jellybean",
  "Pint Size",
  "Chicle",
  "Gummy Bear",
  "Half Pint",
  "Pinkie",
  "Nibbles",
  "Kids’ Table",
  "Skittle",
  "Snacks",
  "Twig",
  "Bug",
  "Tidbit",
  "Gus Gus",
  "Cricket",
  "Trike",
  "Mouse",
  "Porker",
  "My Little Pony",
  "Lil Sis",
  "Fatty",
  "Polly Pocket",
  "Nugget",
  "Vroom Vroom",
  "Bad Mama",
  "Lady",
  "Hot Mama",
  "Naughty Girl",
  "Ranger",
  "Foxy Lady",
  "Naughty Boy",
  "Farmboy",
  "Sweet Thang",
  "Jailbait",
  "Cowboy",
  "The Hunk",
  "Miniskirt",
  "Cowgirl",
  "Bad Boy",
  "High Heels",
  "Wild Girl",
  "Bad Girl",
  "Saucy",
  "Coyote Joe",
  "Stepchild",
  "The Goon",
  "Craigslist",
  "Swamp Thing",
  "Pavement Face",
  "Die Hard",
  "Junkyard",
  "Squeaker",
  "Milk Dud",
  "Junk Bait",
  "Sawdust",
  "Half Life",
  "Vulture Bait",
  "Sawbones",
  "Dumptruck",
  "Roadkill",
  "Troublemaker",
  "Garbage Truck",
  "OK Suzy",
  "Whole Paycheck",
  "Wheezy",
  "Sasquatch",
  "Dents Ahoy",
  "The Zit",
  "The Joker",
  "Grandma",
  "Penny Loafer",
  "Scarface",
  "The Pope",
  "Bingo Champ",
  "Dracula",
  "Gandalf",
  "Prune Juice",
  "Rasputin",
  "Dumbledore",
  "Beauty Queen",
  "Grandpa",
  "Father Time",
  "Prom Queen",
  "Stonehenge",
  "Nursing Home Dropout",
  "Murder She Wrote",
  "Benjamin Franklin",
  "Depends",
  "Lucy",
  "Grumpy",
  "Gravebait",
  "TVLand",
  "Betty White",
  "Quaker Oats",
  "Sunshine State",
  "Gramps",
  "Metamucil",
  "The Old Testament",
  "Shakespeare",
  "Clair de Lune",
  "Jane Eyre",
  "Harvard",
  "Einstein",
  "Jane Austen",
  "John Milton",
  "Chardonnay",
  "Oxford",
  "Charlotte Bronte",
  "401(k)",
  "Cambridge",
  "Je Ne Sais Quois",
  "Foie Gras",
  "Ivory Fender",
  "Mendelssohn",
  "Gilgamesh",
  "PhD",
  "Beethoven",
  "Charlotte Bronte",
  "String Theory",
  "Lisa Frank",
  "Uni-car",
  "Princess Celestia",
  "Emperor of Dreams",
  "Princess of Butterflies",
  "Twilight Sparkle",
  "Adventure Time",
  "The Duke of Willow Trees",
  "Apple Bloom",
  "Night Splendor",
  "Empress Violet",
  "Sparklebright",
  "Wizard of Rainbows",
  "Count Giggles",
  "Rainbow Forest",
  "Magic Puppy",
  "Shiny",
  "Gumdrop Chariot",
  "Glitter Train",
  "Fluttershy",
  "Glitter Boat",
  "Fab Four-Door",
  "Pinkie Pie",
  "The Rainbow Chinchilla",
  "AvaCar",
  "Doc Hudson",
  "Mystique",
  "Baby Blue",
  "Dory",
  "Periwinkle",
  "Baloo",
  "Gonzo",
  "Poseidon",
  "Big Blue",
  "Ice Cube",
  "Serenity",
  "Blue Devil",
  "Ice Ice Baby",
  "Shark Attack",
  "Blue Dolphin",
  "Jaws",
  "Smurf",
  "Blueberry",
  "Leonardo",
  "Sonic",
  "Bluedini",
  "Mako",
  "Street Genie",
  "Cookie Monster",
  "Megamind",
  "Sully",
  "Dinoco Blue",
  "Mr. Freeze",
  "Tidal Wave",
  "Alien",
  "Green Lantern",
  "Ninja Turtle",
  "Chick Hicks",
  "Green Machine",
  "Picklemobile",
  "Clover",
  "Gumby",
  "Poison Ivy",
  "Dragonfly",
  "Irish Lass",
  "Ribbet",
  "Emerald",
  "Kermit",
  "The Booger",
  "Flubber",
  "Kiwi Kruiser",
  "The Green Goddess",
  "Frogger",
  "Little Monster",
  "The Hulk",
  "Green Almighty",
  "Mean Green",
  "Toyoda",
  "Green Giant",
  "Mike Wazowski",
  "Toyoshi",
  "Green Hornet",
  "Mr. Green",
  "Zombie",
  "Banana Splitz",
  "Ducky",
  "Minion Mobile",
  "Bananamobile",
  "Electricity",
  "Python",
  "Big Bird",
  "Firefly",
  "Solar Flare",
  "Blonde Babe",
  "Honeylemon",
  "Spicy Mustard",
  "Blondie",
  "Illuminati",
  "Sunflower",
  "Bumble Bee",
  "Lemon",
  "Sunshine",
  "Buttercup",
  "Lightning",
  "Tequila Sunrise",
  "Citron",
  "Lightning Bug",
  "Tweety Bird",
  "Cruisin' Canary",
  "Luigi",
  "Wolverine",
  "Del Sol",
  "Mellow Yellow",
  "Yellowjacket",
  "Butterfinger",
  "General Lee",
  "Pulp Patrol",
  "Cheddar",
  "Hot Wheels",
  "Pulperizer",
  "Cheeto",
  "Julius",
  "Pulpetrator",
  "Chucky",
  "Kenny McCormick",
  "Pumpkin Eater",
  "Clementine",
  "Kumquat Kruiser",
  "Sly Fox",
  "Creamsicle",
  "Lady Marmalade",
  "Sunkist",
  "Crush",
  "Michaelangelo",
  "Tang",
  "Fireball",
  "Nemo",
  "Tangerine",
  "Flamer",
  "Oompa Loompa",
  "The Fox",
  "Flying Carrot",
  "Peel Out",
  "Tiger",
  "Blushing Beemer",
  "Hamm",
  "Pink Cadillac",
  "Bubble Gum",
  "Hot Mama",
  "Pink Lemonade",
  "Cameo",
  "Hot Rod Pink",
  "The Pink Panther",
  "Carberry Daiquiri",
  "Lottie",
  "Pinky",
  "Carnation",
  "Madamoiselle",
  "Pixie",
  "Cherry Blossom",
  "Malibu Barbie",
  "Rosebud",
  "Cotton Camry",
  "Miss Piggy",
  "Rosette",
  "Dolly",
  "Peaches",
  "Strawberry Street",
  "Ford Fuchsia",
  "Peony",
  "Tickle Me Pink",
  "Gumdrop",
  "Peppermint Pistons",
  "Valentine",
  "Amethyst",
  "Karma",
  "Purple People Eater",
  "Barney",
  "Mad Minion",
  "Ramone",
  "Cheshire Cat",
  "Mythic",
  "Stella",
  "Cosmo",
  "Nebula",
  "Tanzanite",
  "Dark Spell",
  "Orchid",
  "Twilight",
  "Darkwing Duck",
  "Pandora",
  "Ultraviolet",
  "Dino",
  "Pansy",
  "Ursula",
  "Disco Inferno",
  "Purple Cruiser",
  "Violet",
  "Grape Soda",
  "Purple Haze",
  "Wild Berry",
  "Holley Shiftwell",
  "Purple Lotus",
  "Willy Wonka",
  "Anonymous",
  "James Bond",
  "Silver Lightning",
  "Axiom",
  "Knight",
  "Silver Surfer",
  "Bender",
  "Mercury",
  "Soul Ride",
  "Bullet",
  "Metalhead",
  "Spark Plug",
  "Chrome Sweet Chrome",
  "Moonlight Rider",
  "Sterling",
  "DeLorean",
  "Pewter",
  "Stormy",
  "Heavy Metal",
  "Robo Car",
  "Sylvia",
  "Hi-Ho Silver",
  "Rocket Fuel",
  "The Razor",
  "Invincible",
  "Scythe",
  "Titanium",
  "Iron Man",
  "Silver Fox",
  "Tron",
  "American Eagle",
  "Gold Stud",
  "Krugerrand",
  "Bling Bling",
  "Golden Girl",
  "Lady Luck",
  "Champagne",
  "Golden Gun",
  "Lucky",
  "Champion",
  "Goldfinger",
  "Nugget",
  "Chardonnay",
  "Goldilocks",
  "Pharaoh",
  "Cleopatra",
  "Goldschläger",
  "Pixie Dust",
  "Crown Royal",
  "Great Gatsby",
  "Olympia",
  "Duchess",
  "Honey",
  "Queen Bee",
  "Gold Digger",
  "Jackpot",
  "Star",
  "Gold Rush",
  "King Midas	",
  "Xoul",
  "ShaperDown8",
  "KS50",
  "Tks",
  "Tksb",
  "Mi alma",
  "Alma para ti",
  "Exemunden",
  "XIVCrash",
  "Arodix",
  "C'est mustano",
  "Cool Ist'aMust",
  "MeMustang 8",
  "Mustanev 8",
  "Mxlr8",
  "Maximus",
  "Racer V8",
  "speedX MV8",
  "XLR",
  "RXL",
  "LRX",
  "LXR",
  "NXS",
  "CVX",
  "ZRX",
  "TV8",
  "MV8",
  "UV8",
  "XL8",
  "LX8",
  "VT8",
  "VX8",
  "9LR",
];

module.exports = carnames;